### ISSUE TITLE
No-std support for core runtime

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1525]
This is a tracking issue for [`no-std`](https://rust-embedded.github.io/book/intro/no-std.html) support in Wasmer.  `no-std` is useful for running in constrained environments without an operating system.   This issue is only about `no-std` for the core runtime and helper crates, compilers and the JIT engine are out of scope.

- [ ] wasmerio/wasmer-reborn#194 `wasm-common` `no-std` support 
- [ ] wasmerio/wasmer-reborn#195 `wasmer-vm` `no-std` support
- [ ] wasmerio/wasmer-reborn#196 `wasmer-engine` `no-std` support
- [ ] wasmerio/wasmer-reborn#198 `wasmer-object` `no-std` support
- [ ] wasmerio/wasmer-reborn#197 `wasmer-engine-native` `no-std` support
- [ ] wasmerio/wasmer-reborn#199 `wasmer-compiler` `no-std` support

TODO: decide if the `wasmer` API itself should have `no-std` support and what it means if it doesn't

Some of the tasks above may be able to be simplified if we create more intermediate crates to more finely divide the subset that is `no-std` from the regular version of the crate.  Alternatively, crates can just have a reduced functionality, `no-std` mode.

This change is low priority as we don't have any active interest in `no-std` support and some of the changes seem non-trivial.  Additionally, there will be overhead to maintaining these crates as `no-std` so we may want to explicitly decide that we do not want to support `no-std`.

Regardless, if you're interested in this feature and willing to contribute, please let us know!

**Comment by MarkMcCaskey** [comment]
Because we're no longer actively investigating or planning to do this right now I'm closing these issues.  We may be open to implementing no-std support for Wasmer in the future but the overhead of maintaining it without clear and active use cases right now seems like the wrong trade off.
