### ISSUE TITLE
Missing Docs?

### ISSUE THREAD

**Issue by fireproofsocks** [wasmerio/wasmer#531]
### Summary

The documentation does not provide enough details to actually use the software.  Rather, some highly technical guesswork is required.

### Additional details

A few specifics -- this installation command:

```
curl https://get.wasmer.io -sSfL | sh
```

does not specify that you must add `source .wasmer/wasmer.sh` into your `.bash_profile` or equivalent.  Experienced developers may guess to take that step, but the formal instructions are hardly the place for assumptions.

Next, the "examples" are too hypothetical to actually be useful.  E.g. 

```
wasmer run examples/php.wasm
```
might conceivably work, but you need to mention that you must actually download a package first.

A more effective example must show real and concrete steps.  Eventually I found this git page and noticed that it had an `examples/` folder that seemed to correspond to the commands listed.  However, the examples do not work with the exception of `wasmer run examples/lua.wasm` which does open up a Lua prompt.  

The PHP example is confounding because PHP is never used in this context.  A better example would be to create a sample `hello.php` file with some content, e.g. 
```
<?php
print "Hello WASM!";
```
Then run it via `wasmer run examples/php.wasm hello.php`

I think the `sqlite` example falls into the same boat, but I am not familiar enough with it to figure out a viable way to make this syntax work.

NGINX doesn't appear to work at all:
```
wasmer run examples/nginx/nginx.wasm -- -p examples/nginx -c nginx.conf
nginx: [emerg] mkdir() "examples/nginx/client_body_temp" failed (1: Operation not permitted)
```

Finally, the sentence that says "Installing Wasmer through wasmer.io includes wapm, the WebAssembly package manager." must be clarified.  I've been trying for hours and I can't find `wasm` anywhere.

I know you guys must be working on the hard stuff, so sorry to bother with these trivial details, but a few more clarifications would go a long way in onboarding other developers and interested parties.  Thanks!

**Comment by MarkMcCaskey** [comment]
Thanks!  This is a good reminder!  I had the same reaction when I first saw the website.  We're in the process of redoing it and we'll keep this in mind!

Addressing some specific points:
> issues with NGINX

Yeah, it's pretty flakey, if nginx fails it doesn't clean up files it creates and won't work unless you remove them, `rm examples/nginx/*temp` should fix it.

> I've been trying for hours and I can't find wasm anywhere

The package manager is wa**p**m ([wapm.io](https://wapm.io)), it's an easy mistake to make though!
 More docs and a tutorial could help here

> does not specify that you must add source .wasmer/wasmer.sh into your .bash_profile or equivalent. 

I believe the installer attempts to add it automatically and prints out a message explaining how to do it if it can't, [here](https://github.com/wasmerio/wasmer/blob/master/install.sh#L130). I do agree that this information should exist in another place though

Here are some things I think we should do to begin to address this:

## TODO:
- [ ] Add info about NGINX to README
- [ ] Add example PHP program and a README in examples
- [ ] Add info about install (maybe in Github Wiki?)
- [ ] Add some tutorials

Let me know if you have any other suggestions!

**Comment by syrusakbary** [comment]
We simplified the README removing most examples (but keeping lua).

We also created a new documentation site: https://docs.wasmer.io/ that should help on starting with Wasmer!

Let us know if you have more suggestions! Closing the issue meanwhile :)
